name: herdnet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy


  - pip:
     - albumentations==1.0.3
     - fiftyone==0.24.1
     - hydra-core==1.3.2
     - opencv-python==4.10.0.84
     - pandas==2.2.2
     - pillow==10.4.0
     - scikit-image
     - scikit-learn
     - scipy==1.9.3
     - wandb==0.19
     - gdown==5.2.0
     - jupyterlab==3.4.4
     - torch==2.5.1
     - matplotlib
     - torchvision==0.20.1
     - tqdm==4.66.5
     - loguru==0.7.3