name: herdnet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.19.2

  - pip:
     - albumentations==1.0.3
     - fiftyone==0.14.3
     - hydra-core==1.1.0
     - opencv-python==4.5.1.48
     - pandas==1.2.3
     - pillow==8.2.0
     - scikit-image==0.18.1
     - scikit-learn==1.0.2
     - scipy==1.6.2
     - wandb==0.10.33
     - gdown==5.2.0
     - jupyterlab==3.4.4
     - torch==1.9.0
     - matplotlib==3.4.2
     - torchvision==0.19.0
     - tqdm==4.66.5