channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - gdal
  - numpy
  - scipy
  - pandas

  - pip:
      - timm==1.0.19
      - albumentations==1.0.3
      # - fiftyone==1.0.1
      - hydra-core==1.3.2
      - opencv-python==4.10.0.84
      - pillow==10.4.0
      - scikit-image
      - scikit-learn
      - wandb==0.20.1
      - gdown==5.2.0
      #- jupyterlab==3.4.4

      #- matplotlib
      # - torchvision==0.20.1
      - tqdm
      - loguru
      #- shapely==2.1.1
      - seaborn==0.13.2