wandb_notes: |
  """default Settings from From crowd to herd counting on aed with timm DLA34 model"""
  "full image evaluation with stitching"
  "model loaded from previous checkpoint"

defaults:
  - /losses: herdnet_publication
  - /datasets: aed_train_crop_eval_full_size
  - /training_settings: delplanque2022_evaluator_stitcher
  - /model: HerdNetTimmDLA34_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_aed'
wandb_entity: 'karisu'
wandb_run: 'timm_DLA34_full_eval'
wandb_tags: ['timmDLA', 'aed','dla34', 'default_setting', "exp1", "eval_full"]
seed: 1
device_name: null

model:
  load_from: /raid/cwinkelmann/herdnet/outputs/2025-09-12/10-40-54/best_loss_model.pth # dla34 dr2 - https://wandb.ai/karisu/herdnet_aed/runs/70nu9hbg/logs
#  kwargs:
#    down_ratio: 4
#training_settings:
#  batch_size: 4
#  evaluator:
#    kwargs:
#      lmds_kwargs:
#        scale_factor: 8 # # dr=2 -> scale_factor 16, dr=4 -> 8, dr=8 -> 4, dr=16 -> 2 in the non patching case

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

