wandb_notes: |
  "default Settings from From crowd to herd counting on aed with custom DLA34 model"


defaults:
  - /losses: herdnet_publication
  - /datasets: aed
  - /training_settings: delplanque2022_val_loss
  - /model: Herdnet34_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_aed'
wandb_entity: 'karisu'
wandb_run: 'custom_DLA34_publication_setting'
wandb_tags: ['customDLA', 'aed','dla34', 'boxcenter', 'default_setting', "exp1"]
seed: 1
device_name: null

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

