# Settings from From crowd to herd counting: How to precisely detect and count African mammals using aerial imagery and deep learning? paper, Deplanque2023

defaults:
  - /losses: herdnet_publication
  - /datasets: delplanque2022
  - /training_settings: delplanque2022_evaluator
  - /model: Herdnet34_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_deplanque2022'
wandb_entity: 'karisu'
wandb_run: 'custom_DLA34_publication_setting'
wandb_tags: ['customDLA', 'delplanque','dla34', 'boxcenter', 'default_setting', "exp1"]
seed: 1
device_name: null

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

