wandb_notes: |
  """default Settings from From crowd to herd counting on eikelboom 2019 dataset with timm DLA102 model"""
defaults:
  - /losses: herdnet_publication
  - /datasets: eikelboom2019_crop_train_crop_val_aug_default
  - /training_settings: delplanque2022_val_loss
  - /model: HerdnetTimmDLA102_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_eikelboom'
wandb_entity: 'karisu'
wandb_run: 'eikelboom_dla102_train_crop_eval_crop_publication'
wandb_tags: ['timmDLA', 'eikelboom','dla102', 'default_setting', "exp1"]
seed: 1
device_name: null

#training_settings:
#  lr: 0.0001

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

