wandb_notes: |
  Testing the effect of the model size  leads to better numbers, here DLA34
  

defaults:
  - /losses: iguana_herdnet_publication
  - /datasets: floreana_crop_train_corrected_crop_val_corrected_aug_default
  - /training_settings: delplanque2022_evaluator_quick
  - /model: HerdnetTimmDLA60_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'x13_model_size'
wandb_entity: 'karisu'
wandb_run: 'DLA60 Floreana'
wandb_tags: ['dla', 'dla_60', 'dr2', "exp12", "eval_crop", "train_crop", "corrected", "floreana"]
seed: 1
device_name: null


# overrides
training_settings:
  lr: 1.0e-05
  epochs: 150
  batch_size: 4
  valid_freq: 1

model:
  kwargs:
    down_ratio: 2

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

