wandb_notes: |
  Testing if the hyperparameters lead to better numbers, for ference here the default augmentation

defaults:
  - /losses: herdnet_publication
  - /datasets: fernandina_crop_train_corrected_crop_val_corrected_aug_default
  - /training_settings: delplanque2022_evaluator_stitcher
  - /model: HerdNetTimmDLA34_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'x10_hyp_aug_opt'
wandb_entity: 'karisu'
wandb_run: 'x10_hyp_opt__fernandina_cvat_corr_dla34_pub_train_tile_eval_tile_aug_default'
wandb_tags: ['dla', 'dla_34', 'aug_default', "exp10", "eval_crop", "train_crop", "corrected"]
seed: 1
device_name: null


# overrides
# overrides
training_settings:
  lr: 1.0e-03
  epochs: 75
  batch_size: 5
#model:
##     dla34 dr2
#    load_from: /raid/cwinkelmann/herdnet/outputs/2025-10-06/20-54-02/best_model.pth # https://wandb.ai/karisu/herdnet_iguana_cvat_corr/runs/foygf9rd/logs
#

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

