wandb_notes: |
  Testing if a lower or higher down ratio for DLA34 (here dr2) leads to better numbers, here with the default augmentations
  

defaults:
  - /losses: herdnet_publication
  - /datasets: floreana_crop_train_corrected_crop_val_corrected_aug_default
  - /training_settings: delplanque2022_evaluator_stitcher
  - /model: HerdNetTimmDLA34_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'x12_dr'
wandb_entity: 'karisu'
wandb_run: 'x12_hyp_DR2_to_8_fernandina_cvat_corr_dla34_pub_train_tile_eval_tile_aug_def'
wandb_tags: ['dla', 'dla_34', 'dr2', "exp12", "eval_crop", "train_crop", "corrected"]
seed: 1
device_name: null


# overrides
# overrides
training_settings:
  lr: 1.0e-03
  epochs: 150
  batch_size: 5
model:
  kwargs:
    down_ratio: 2

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

