# Compare Hyperparameters for timmdla34

program: ./tools/train_cli.py
method: bayes

project: 'herdnet_iguana_sweep_train_3'
entity: 'karisu'

metric:
  goal: maximize
  name: f1_score


# Add early termination
early_terminate:
  type: hyperband
  min_iter: 10
  eta: 3

parameters:
  # Reduce training epochs for sweep
  model.kwargs.down_ratio:
    values: [ 4 ]

  training_settings.batch_size:
    values: [ 32, 16 ]

  training_settings.epochs:
    values: [ 50 ]

  training_settings.lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.01

  training_settings.weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001



command:
  - ${env}
  - python
  - ${program}
  - --config-name=x15_2_hyper_parameter_optimisation_floreana
  - --config-path=../configs/experiment_publication_reproduction
  - ${args_no_hyphens}