wandb_notes: |
  "train on random crops of floreana, evaluate on crops floreana images"
  "trained with dinov2_small"

defaults:
  - /losses: herdnet_winning
  - /datasets: iguana_all_winning_all_vs_fcd_train_crop
  - /training_settings: delplanque2022_evaluator_stitcher_best
  - /model: HerdnetTimmDLA102_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_iguana'
wandb_entity: 'karisu'
wandb_run: 'x5_iguana_winning_corr_dla102_pub_train_crop_eval_full_aug_all'
wandb_tags: ['dla', 'dla_102', 'default_setting', "exp1", "eval_full", "train_crop", "corrected"]
seed: 1
device_name: null

training_settings:
  lr: 1.0e-03
  warmup_iters: 50

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

