wandb_notes: |
  Hopefully the last training I need to do which combines the best annotations, training settings etc

defaults:
  - /losses: herdnet_iguana_high_recall
  - /datasets: iguana_marchena_sample
  - /training_settings: delplanque2022_evaluator_NoStitcher
#  - /model: HerdNetTimmDLA34_dr2_imagenet
#  - /model: dinov2_one_best
  - /model: dinov3_fpn
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'dinov3'
wandb_entity: 'karisu'
wandb_run: 'dinov3'
wandb_tags: ["dino"]
seed: 1
device_name: null



model:
#  load_from: /raid/cwinkelmann/herdnet/outputs/2025-12-03/11-44-45/best_model.pth # https://wandb.ai/karisu/f1_alldata_all_best_DINO/runs/gonz7gta/logs
  kwargs:
    down_ratio: 4
  freeze_backbone: True
#
#training_settings:
#  lr: 1.0e-06
#  batch_size: 25


hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

