wandb_notes: |
  fine tune on full iguana dataset with timm DLA34 model

defaults:
  - /losses: herdnet_iguana
  - /datasets: iguana_all_winning_all_vs_fwk_best_aug
  - /training_settings: delplanque2022_evaluator_stitcher
  - /model: dinov2_one_best
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'f1_alldata_all_best_DINO'
wandb_entity: 'karisu'
wandb_run: 'f1_alldata_all_best_DINO_best_aug'
wandb_tags: ["dino"]
seed: 1
device_name: null


training_settings:
  lr: 1.0e-05
  epochs: 15
  batch_size: 15
  evaluator:
    kwargs:
      lmds_kwargs:
        adapt_ts: 0.3
model:
  load_from: /raid/cwinkelmann/herdnet/outputs/2025-11-13/18-13-52/best_model.pth

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

