trainer: 'Trainer'
epochs: 100
valid_freq: 1
print_freq: 125
batch_size: 25
# optimizer: 'SGD'
optimizer: 'adamW'
lr: 1.0e-05
weight_decay: 0.0005
num_workers: 12
auto_lr:
  mode: 'max'
  patience: 50
  threshold: 1e-4
  threshold_mode: 'rel'
  cooldown: 20
  min_lr: 1e-7
  verbose: True
warmup_iters: 1000

# vizual_fn: "model_vizual"
vizual_fn: visualize_sample
visualiser:
  name: 'HeatMapVisualizer'
  output_dir: ./visualizations


loss_evaluation: null

evaluator:
  name: 'HerdNetEvaluator'
  threshold: 125
  select_mode: 'max'
  validate_on: 'f5_score'
  kwargs:
    print_freq: 25
    lmds_kwargs:
      kernel_size: [9, 9]
      adapt_ts: 0.5
      scale_factor: 1 # was 8 in the non patching case TODO fix this so it is 8 for single use and 1 for patching
      # scale_factor_patching: 1
      up: True

stitcher:
  name: 'HerdNetStitcher'
  kwargs:
    overlap: 120
    down_ratio: ${model.kwargs.down_ratio}
    up: False
    reduction: 'mean'
#stitcher: null