

# name: 'HerdNetTimm'
name: 'HerdNetDINOv2'

# work_dir: "./outputs/"
from_torchvision: False
#load_from: /raid/cwinkelmann/herdnet/outputs/2025-08-10/23-21-57/best_model.pth
load_from: null


resume_from: null
kwargs:
  backbone: 'timm/vit_large_patch14_dinov2.lvd142m'
  pretrained: True
  # pretrained_path: '/home/cwinkelmann/work/Herdnet/data/models/dla34_224/model_best.pth.tar'
  pretrained_path: null
  down_ratio: 4  # was two before
  head_conv: 64 # was 64
  output_channels: [768, 1024, 1280]
  attention_layers: [-8, -6, -4, -3, -2, -1]

freeze: False # Freeze the model, if you want to train only the heads
freeze_backbone: False # Freeze the backbone, if you want to train only the heads