# Settings from From crowd to herd counting: How to precisely detect and count African mammals using aerial imagery and deep learning? paper, Deplanque2023

defaults:
  - /losses: iguana
  - /datasets: floreana_train_corrected_val_corrected
  - /training_settings: delplanque2022_evaluator
  - /model: HerdNetTimmDLA34_dr2_imagenet
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_iguana_training_val_correction'
wandb_entity: 'karisu'
wandb_run: 'DinoV2_train_val_corrected'
wandb_tags: ['iguana', 'dla34', 'DLA', 'timm', 'default_setting', "exp5"]
seed: 1
device_name: null

# Override specific parameters from included configs
model:
  freeze_backbone: True
  kwargs:
    down_ratio: 4
training_settings:
  batch_size: 45
  evaluator:
    kwargs:
      lmds_kwargs:
        scale_factor: 8 # # dr=2 -> scale_factor 16, dr=4 -> 8, dr=8 -> 4, dr=16 -> 2 in the non patching case

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

