# Eikelboom2019 dataset full size configuration file

img_size: [512, 512] # The size of how the images should be processed, mostly important for the tiled prediction
anno_type: 'point'
num_classes: 7 # One class more for the background
collate_fn: null


class_def:
  1: 'Giraffe'
  2: 'Elephant'
  3: 'Zebra'
  4: '-'
  5: '-'
  6: '-'
  7: '-'

train:
  name: 'CSVDataset'

  csv_file: '/home/cwinkelmann/work/Herdnet/data/eikelboom/eikelboom_train/detection_train_0_512/herdnet_format.csv'
  root_dir: '/home/cwinkelmann/work/Herdnet/data/eikelboom/eikelboom_train/detection_train_0_512/Default'

  sampler: null
  augmentation_multiplier: 1

  albu_transforms:
    HorizontalFlip:
      p: 0.5
    MotionBlur:
      p: 0.5
    Normalize:
      p: 1.0

  end_transforms:
    MultiTransformsWrapper:
      FIDT:
        num_classes: ${datasets.num_classes}
        down_ratio: ${model.kwargs.down_ratio}
        radius: 1
      PointsToMask:
        radius: 2
        num_classes: ${datasets.num_classes}
        squeeze: true
        down_ratio: 32

validate:
  name: 'CSVDataset'

  csv_file: '/home/cwinkelmann/work/Herdnet/data/eikelboom/eikelboom_val/detection_val_0_512/herdnet_format.csv'
  root_dir: '/home/cwinkelmann/work/Herdnet/data/eikelboom/eikelboom_val/detection_val_0_512/Default'

  albu_transforms:
    Normalize:
      p: 1.0

  end_transforms:
    DownSample:
      down_ratio: ${model.kwargs.down_ratio}
      anno_type: ${datasets.anno_type}

