wandb_notes: |
  "train on random crops of floreana, evaluate on crops floreana images"
  "trained with dinov2_small"

defaults:
  - /losses: herdnet_winning
  - /datasets: aed_all_winning
  - /training_settings: delplanque2022_evaluator_stitcher_best
  - /model: Dinov2_large_best
  - _self_  # Include this config's content

wandb_flag: True
wandb_project: 'herdnet_aed'
wandb_entity: 'karisu'
wandb_run: 'x5_aed_winning_dinoL_pub_train_full_eval_full_aug_all'
wandb_tags: ['floreana','dinov2', 'Dinov2_small', 'default_setting', "exp1", "eval_crop", "train_full"]
seed: 1
device_name: null


model:
  #   hb555gel
  load_from: /home/cwinkelmann/work/Herdnet/best_models/hb555gel/best_model.pth

hydra:
  run:
    dir: /raid/cwinkelmann/herdnet/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

